### ISSUE TITLE
Feedback for V0.0

### ISSUE THREAD

**Issue by nirandiw** [CS2103JAN2017-F14-B3/main#8]
# ReadMe

1. Acknowledge the original code.

# AboutUs
1. Looks ok for now.

# User Guide
1. Floating tasks do not have a date or time. I see that the floating task in the mock UI has a date/time.
2. 24 hour time format might not be user firendly. 
3. It is good to have examples. But i feel like there are too many examples. Can you pick a set of examples and include only those in the User Guide. Overloading with information might not be useful to the user. 
4. Editing using the task name--> what happens if two tasks has the same name?
5. When deleting the task using the task name --> What happens if two tasks has the same name?
6. You have a lot of feaures. We expect all the features to work properly and you must write tests. Therefore, make sure to start from the basic operation and once it has been implemented properly you can start handling the other features.

**Comment by LiHaoTan** [comment]
Resolved
